root_ckpt_dir: './checkpoint_dir'
device: 'cuda:0'

seed: 10010

mask_trans_name: "hml_momaskplus_hrvq5_nlayer8_cdp0.1_ca" # or "hml_momaskplus_hrvq5_nlayer8_cdp0.1_ic"

time_steps: [18]
cond_scales: [5]
temperature: 1
topkr: 0.9
force_mask: False
cal_mm: True
gsample: True
which_epoch: net_best_fid.tar

ext: evaluation_res_cs5_ts18


matching_pool_size: 32
repeat_time: 20


data:
  name: 'humanml3d'
  unit_length: 4
  root_dir: '/mnt/local-disk/HumanML3D'
  joint_num: 22
  dim_pose: 263 #296 #here we use all features
  fps: 20
  max_motion_length: 196
  motion_length: 128
  max_text_length: 20
  min_motion_length: 40



gen:
  num_samples: 32
  animate: True
  foot_lock: True