exp:
  root_ckpt_dir: './checkpoint_dir'
  root_log_dir: './log'
  name: 'gmr_d292'
  device: 'cuda:0'
  is_continue: False
  is_train: True
  seed: 10306


data:
  name: 'snapmogen'
  unit_length: 4
  root_dir: '/mnt/local-disk/SnapMoGen'
  joint_num: 24
  dim_pose: 292 #1+2+1+24*6, only use local rotations plus root information
  fps: 30
  motion_length: 120


training:
  batch_size: 256
  max_epoch: 100
  lr: 2.0e-4
  milestones: [100_000]
  gamma: 0.1
  warm_up_iter: 200
  log_every: 10
  save_latest: 500
  eval_every_e: 1